version: "3.8"

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: guestbookdb
      MYSQL_USER: guest
      MYSQL_PASSWORD: guest1234
    ports:
      - "3307:3306"

  backend:
    build: ./backend/guestbook
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/guestbookdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: guest
      SPRING_DATASOURCE_PASSWORD: guest1234

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
